### ISSUE TITLE
Can't install in devcontainer

### ISSUE THREAD

**Issue by Hegi** [iliazeus/vscode-ansi#29]
When I try to install this extension inside a `devcontainer` I get error message below.
Note: it was working just fine until today's VS Code update.

```
2024-02-29 02:13:37.997 [info] Getting Manifest... iliazeus.vscode-ansi
2024-02-29 02:13:38.146 [info] Installing extension: iliazeus.vscode-ansi
2024-02-29 02:13:38.703 [warning] Extension signature verification failed with error 'PackageIsUnreadable': iliazeus.vscode-ansi
2024-02-29 02:13:38.706 [error] Error while installing the extension iliazeus.vscode-ansi ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/iliazeus.vscode-ansi-1.1.7'
2024-02-29 02:13:39.706 [error] Invalid: ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/iliazeus.vscode-ansi-1.1.7'
    at oe.B (/vscode/vscode-server/bin/linux-x64/019f4d1419fbc8219a181fab7892ebccf7ee29a2/out/vs/server/node/server.main.js:169:82425)
2024-02-29 02:13:39.712 [error] Extract: ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/iliazeus.vscode-ansi-1.1.7'
    at K.extractUserExtension (/vscode/vscode-server/bin/linux-x64/019f4d1419fbc8219a181fab7892ebccf7ee29a2/out/vs/server/node/server.main.js:169:73803)
    at async oe.u (/vscode/vscode-server/bin/linux-x64/019f4d1419fbc8219a181fab7892ebccf7ee29a2/out/vs/server/node/server.main.js:169:80250)
    at async oe.x (/vscode/vscode-server/bin/linux-x64/019f4d1419fbc8219a181fab7892ebccf7ee29a2/out/vs/server/node/server.main.js:169:82165)
    at async oe.h (/vscode/vscode-server/bin/linux-x64/019f4d1419fbc8219a181fab7892ebccf7ee29a2/out/vs/server/node/server.main.js:169:79783)
```

**Comment by iliazeus** [comment]
From the looks of it, it's an issue with VSCode, not with the extension. I will try to see if I can work around it, but you really should open an issue at https://github.com/microsoft/vscode/issues.

**Comment by Hegi** [comment]
I moved away from the project, so I can no longer reproduce the error on my end. Apologies; and thanks for following up!
